name: Desktop Prod Release

on:
  push:
    branches: [ main ]
    paths:
      - packages/desktop/**
  workflow_dispatch:

jobs:
  call-reusable-build:
    uses: standardnotes/app/.github/workflows/desktop.release.reuse.yml@main
    secrets: inherit
    with:
      channel: prod