name: Desktop Dev

on:
  push:
    branches:
      - develop
    paths:
      - packages/desktop/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/desktop
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn setup
      - run: node ../../scripts/desktop/build.mjs appimage-x64
      - uses: actions/upload-artifact@v2
        with:
          name: 'AppImage'
          path: dist/*.AppImage
