name: Desktop Beta Release

on:
  push:
    branches: [ develop ]
    paths:
      - packages/desktop/**
  workflow_dispatch:

jobs:
  BuildWorkflow:
    uses: standardnotes/app/.github/workflows/desktop.release.reuse.yml@develop
    secrets: inherit
    with:
      channel: beta