name: Sync Repo

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "standardnotes/app"
          source_branch: "refs/remotes/source/*"
          destination_repo: "standardnotes/internal-app"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sleep to allow git-sync to fully complete
        run: sleep 10
        shell: bash

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_PAT_TOKEN }}
          repository: standardnotes/internal-app
          ref: ${{ github.ref }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: peter-evans/create-pull-request@v4
        if: "${{ github.actor != 'dependabot' }}"
        with:
          token: ${{ secrets.CI_PAT_TOKEN }}
          branch: ${{ github.ref }}
          base: main
          title: ${{ steps.extract_branch.outputs.branch }}
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
